# SPDX-FileCopyrightText: 2023 - 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Woodpecker CI server installation tasks
  when: woodpecker_ci_server_enabled | bool
  tags:
    - setup-all
    - setup-woodpecker-ci-server
    - install-all
    - install-woodpecker-ci-server
  block:
    - name: Validate Woodpecker CI server configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Woodpecker CI server
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Woodpecker CI server uninstallation tasks
  when: not woodpecker_ci_server_enabled | bool
  tags:
    - setup-all
    - setup-woodpecker-ci-server
  block:
    - name: Uninstall Woodpecker CI server
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
