# SPDX-FileCopyrightText: 2026 Suguru Hirahara
# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: woodpecker-ci-server-${MOLECULE_DISTRO:-ubuntu2604}-default
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2604}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_result_format: yaml
  inventory:
    group_vars:
      all:
        # Helper variables
        woodpecker_ci_server_debug_service_enabled: false

        # Variables for Woodpecker CI server
        woodpecker_ci_server_uid: 1000
        woodpecker_ci_server_gid: 1000
        woodpecker_ci_server_scheme: http
        woodpecker_ci_server_hostname: localhost
        woodpecker_ci_server_container_labels_traefik_enabled: false
        woodpecker_ci_server_http_bind_port: 8000
        woodpecker_ci_server_database_type: sqlite3
        woodpecker_ci_server_provider: gitea
        woodpecker_ci_server_config_agent_secret: secret
        woodpecker_ci_server_config_gitea_url: https://example.com
        woodpecker_ci_server_config_gitea_client: client
        woodpecker_ci_server_config_gitea_secret: secret
  env:
    # Workaround for https://github.com/ansible/molecule/issues/4391
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..:/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:~/.ansible/roles
verifier:
  name: ansible
